const etapas=[
{titulo:'1. Pergunta e plano',itens:['Lemos o regulamento, critérios e prazos da feira.','Definimos uma pergunta investigável ou problema de projeto.','Registramos hipótese ou critérios da solução.','Planejamos variáveis, comparação, dados e repetições.','Submetemos riscos e procedimentos ao orientador antes de testar.']},
{titulo:'2. Investigação',itens:['Mantemos diário com datas, decisões e resultados.','Usamos fontes confiáveis e registramos as referências.','Executamos somente procedimentos aprovados e supervisionados.','Guardamos dados originais, inclusive resultados inesperados.','Analisamos limites e não alteramos dados para confirmar a hipótese.']},
{titulo:'3. Comunicação',itens:['O título e o resumo explicam a ideia central.','O painel diferencia pergunta, método, resultados e conclusão.','Gráficos têm título, unidades e legenda legíveis.','Créditos identificam equipe, orientação e fontes.','Treinamos uma explicação curta e respostas sobre limitações.']},
{titulo:'4. Dia da feira',itens:['Confirmamos mesa, energia, internet e acessibilidade.','Transportamos materiais em embalagens seguras.','Levamos extensão ou equipamento apenas quando autorizado.','Removemos dados pessoais de participantes e imagens sem autorização.','Definimos montagem, revezamento e desmontagem responsável.']}
];
const total=etapas.reduce((n,e)=>n+e.itens.length,0);function percentual(q){return total?Math.round(q/total*100):0}
if(typeof document!=='undefined'){const chave='feira-ciencias-v1';let marcados=new Set(JSON.parse(localStorage.getItem(chave)||'[]'));function render(){lista.innerHTML=etapas.map((e,a)=>`<article><h2>${e.titulo}</h2>${e.itens.map((x,b)=>{const id=`${a}-${b}`;return`<label><input type="checkbox" data-id="${id}" ${marcados.has(id)?'checked':''}><span>${x}</span></label>`}).join('')}</article>`).join('');placar.textContent=`${marcados.size} de ${total} concluídos`;barra.style.width=`${percentual(marcados.size)}%`;document.querySelectorAll('[data-id]').forEach(c=>c.addEventListener('change',()=>{c.checked?marcados.add(c.dataset.id):marcados.delete(c.dataset.id);localStorage.setItem(chave,JSON.stringify([...marcados]));render()}))}limpar.addEventListener('click',()=>{marcados.clear();localStorage.removeItem(chave);render()});render()}
if(typeof module!=='undefined')module.exports={etapas,total,percentual};
